apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-deployment
  namespace: devops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
      - name: devops-demo
        image: YOUR_DOCKERHUB_USERNAME/devops-demo:latest
        ports:
        - containerPort: 3000
