apiVersion: v1
kind: Service
metadata:
  name: devops-demo-service
  namespace: devops-demo
spec:
  type: LoadBalancer
  selector:
    app: devops-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

